import Head from 'next/head';

const Header = () => {
  return (
    <>
      <Head>
         <title>InfoTab - Soluções em informática e segurança eletrônica.</title> 
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-primarycolor text-white'>
        <header className='container mx-auto flex justify-between items-center h-[69px]'>
            <div className="logo">
              <h1 className="text-4xl font-light">InfoTab</h1>
            </div>
            <nav className='flex justify-between'>
              <ul className='flex justify-between '>
                <li className='px-2 py-1'><a href="#" className='font-light text-base'>Home</a></li>
                <li className='px-2 py-1'><a href="#" className='font-light text-base'>Serviços</a></li>
                <li className='px-2 py-1'><a href="#" className='font-light text-base'>Nossa história</a></li>
                <li className='px-2 py-1'><a href="#" className='font-light text-base'>Contato</a></li>
              </ul>
            </nav>
          </header>
      </div>
    </>
  )
}

export default Header;