import Head from 'next/head';  
import React from 'react';
import { VscMenu, VscClose } from "react-icons/vsc";
function Header() {

  const [nav, setNav] = React.useState(false);
  const [textColor, setTextColor] = React.useState('white');

  function handleNav() {
    setNav(!nav);
  } 

  return (
    <>
      <Head>
         <title>InfoTab - Soluções em informática e segurança eletrônica.</title> 
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-primarycolor text-white w-full z-999 ease-in duration-300'>
        <div className='container mx-auto flex justify-between items-center py-2 only:px-4'>
          <div>
            <a href="/" className='font-Lexand font-light '><h1 className='text-base sm:text-lg md:text-xl'>infoTab</h1></a>
          </div>
          <ul className='hidden sm:flex font-Lexend font-light text-base'>
            <li className='p-2 hover:font-semibold'><a href="#">Home</a></li>
            <li className='p-2 hover:font-semibold'><a href="#">Serviços</a></li>
            <li className='p-2 hover:font-semibold'><a href="#">Nossa História</a></li>
            <li className='p-2 hover:font-semibold'><a href="#">Contato</a></li>
          </ul> 
          {/* Mobile button */}
          <div onClick={handleNav} className='block sm:hidden z-20'>  
            { nav ? (
                <VscClose size={32} style={{color: `${textColor}`}} />
              ) : (
                <VscMenu size={32}  />
              )             
            }  
          </div>
          {/* Mobile mobile */}
          <div className={nav ? 'sm:hidden absolute top-0 left-0 right-0 bottom-0 flex justify-center items-center w-full h-screen bg-primarycolor text-white ease-in duration-300 z-10' : 'sm:hidden absolute top-0 left-[-100%] right-0 bottom-0 flex justify-center items-center w-full h-screen bg-primarycolor text-white ease-in duration-300'}>
            <ul className='text-center font-Lexend text-xl font-light'>
              <li className='p-2 hover:font-semibold'><a href="#">Home</a></li>
              <li className='p-2 hover:font-semibold'><a href="#">Serviços</a></li>
              <li className='p-2 hover:font-semibold'><a href="#">Nossa História</a></li>
              <li className='p-2 hover:font-semibold'><a href="#">Contato</a></li>
            </ul>
          </div>
        </div>
      </div>
     
    </>
  )
}

export default Header;